# This is a generated file. Not intended for manual editing.
version: "3.9"
services:
  evently.api:
    build:
      context: "D:\\Study\\dev\\Evently\\Evently"
      dockerfile: "src/API/Evently.Api/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57400"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "eventlyapi:dev"
    ports:
    - "127.0.0.1:57001:57000"
    - "127.0.0.1:57201:57200"
    - "127.0.0.1:57401:57400"
    volumes:
    - "D:\\Study\\dev\\Evently\\Evently\\src\\API\\Evently.Api:/app:rw"
    - "D:\\Study\\dev\\Evently\\Evently:/src:rw"
    - "C:\\Users\\Admin\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\Admin\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2024.3.2\\\
      Linux64:/opt/JetBrains/RiderDebuggerTools"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2024.3.2\\bin\\backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "C:\\Users\\Admin\\AppData\\Local\\JetBrains\\Rider2024.3\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2024_12_24_13_19_34:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
